### ISSUE TITLE
Error pops up when I tried to catkin_make the code

### ISSUE THREAD

**Issue by LevineYang** [coincar-sim/coincarsim_getting_started#1]
Error pops up when I try to catkin_make the code... when I tried to catkin build, there is "No module named catkin", orz... any help would be greatly appreciated!

-- +++ processing catkin package: 'util_geo_coordinates_ros'
-- ==> add_subdirectory(util_geo_coordinates_ros)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find BoostPython (missing: BoostPython_LIBRARIES
  BoostPython_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  mrt_cmake_modules/cmake/Modules/FindBoostPython.cmake:104 (find_package_handle_standard_args)
  mrt_cmake_modules/cmake/Modules/FindAutoDeps.cmake:87 (find_package)
  util_geo_coordinates_ros/CMakeLists.txt:16 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/jt/coincarsim_getting_started/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/jt/coincarsim_getting_started/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by ZhangHongjuan** [comment]
Hi, I am just wandering how do you "catkin_make" the codes? I followed up the instruction, and built the project succesfully. but it used "catkin build" command instead of "catkin_make". But in my case, I do want to use "catkin_make" to build the codes. Could please give me any hints?

**Comment by m-naumann** [comment]
Hi, `catkin_make` is very outdated, you should use `catkin build` instead. See also https://catkin-tools.readthedocs.io/en/latest/index.html

I see no reason for building with `catkin_make`, could you explain why you think that'd be better?
