### ISSUE TITLE
roslaunch _whole_framework has errors due to only python3 present in Ubuntu20.04

### ISSUE THREAD

**Issue by Wing-ka-king** [coincar-sim/coincarsim_getting_started#12]
Hi! I'm using Ubuntu 20.04 and neotic ros installation.

My build completed successfully but on roslaunching the _whole_framework.launch, I get some errors with frame and objectStateArray in rviz. 
Upon further checking the logs in the terminal, it says `/usr/bin/env 'python' : No such file or directory` for process [map_frame_to_utm_tf_publisher-1] and other object initialization processes for v1, v2, p5, p6.
I suppose it is because by default only python3 is provided with newer Ubuntu releases. Can it be fixed by simply changing to `/usr/bin/env python3` in all those object initialization files? or something more needs to be done to migrate to python3.

Thanks

**Comment by m-naumann** [comment]
As workaround, changing the shebang is okay. See http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs. Thanks for reporting.

edit: Fix is on the way

**Comment by m-naumann** [comment]
Fixed with https://github.com/KIT-MRT/mrt_cmake_modules/commit/76785dfb07126818070cbe0b4bb82977357ec187

Please confirm and close if solved

**Comment by Wing-ka-king** [comment]
Yes, this is fixed now.
