### ISSUE TITLE
What is the role of sample_hull.xml ?

### ISSUE THREAD

**Issue by arvindkyutech** [coincar-sim/coincarsim_getting_started#14]
I want to load my own map. Lanelet file I can generate from JOSM but generating sample_hull.xml, sample_hull_pedestrian.xml is not clear to me. Can you please guide, how generate these files inside the package simulation_initialization_ros_tool/res/ ?

**Comment by m-naumann** [comment]
This file just describes the hull (in the meaning of appearance) of objects. You can just take the sample hull for vehicles and the sample hull pedestrian for pedestrians

**Comment by arvindkyutech** [comment]
Thank you so much for your help. Got it now it's working fine.
