### ISSUE TITLE
CommonRoad Scenarios in CoincarSIM?

### ISSUE THREAD

**Issue by arvindkyutech** [coincar-sim/coincarsim_getting_started#15]
CommonRoad already has very large collection of scenarios. Can you please guide steps to load CommonRoad map and objects in CoincarSIM for cooperative behavior?

**Comment by m-naumann** [comment]
@arvindkyutech Did you manage to load the scenarios? They key problem I see is that the CommonROAD maps are not in lanelet2 format, but in a modified lanelet1 format.

**Comment by arvindkyutech** [comment]
@m-naumann Thank you so much for your comment. Yes lanelet1 format is the major issue, is there any library support to convert CommonROAD scenario file to lanelet2 format. Sorry for asking too many things, simple hint will also be a great help.

**Comment by m-naumann** [comment]
Sorry, just saw this. I don't know any library to do this conversion.

**Comment by arvindkyutech** [comment]
Hi, Regarding Scenario, I can load arbitrary scenarios created in JOSM, which fulfils my purpose. CoincarSIM is an excellent simulator. Especially its support to model V2X messages.
