### ISSUE TITLE
using catkin_cmake

### ISSUE THREAD

**Issue by ZhangHongjuan** [coincar-sim/coincarsim_getting_started#2]
Hi all, I built the project succesfully with "catkin build", but I want to use "catkin_cmake" to build the project, so that I can debug it with my IDE clion. any idea is appreciated!

**Comment by m-naumann** [comment]
I don't use CLion, but maybe that helps: https://github.com/ethz-asl/programming_guidelines/wiki/CLion

Did you source ROS before starting CLion?
