### ISSUE TITLE
planning

### ISSUE THREAD

**Issue by xiaozhi12345678** [coincar-sim/coincarsim_getting_started#3]
Hi, I use catkin build to build the project and it works.I have two issues here. 
The first is the regulatory element doesn't come up in the rviz,even if I choose the option,and I replace the .osm map of myself.
The second is I want to input the start point and destination ,the rviz can auto to  show the routing.How can I do it?I see you use trj.osm to guide the car,is it the only way that make the car go?
thank you!

**Comment by m-naumann** [comment]
These questions are already answered in https://github.com/coincar-sim/lanelet_rviz_plugin_ros/issues/2#issuecomment-478651870
